### ISSUE TITLE
npm run compile shows many errors

### ISSUE THREAD

**Issue by ammarRajabA** [Cezerin2/cezerin2-admin#104]
Thank you for your great work.

I'm cloning the "typescript" repos (admin, server, and store), running `npm install` then `npm run compile` but tsc seems to print many errors.

Am I missing something?

The mono repo works fine however but it's a bit old and it uses js.

Below is the error log I'm getting.

[log.txt](https://github.com/Cezerin2/cezerin2-admin/files/4846397/log.txt)

**Comment by Himadu2000** [comment]
Thank you for issue, I'm in making of the typescript, you can ignore the errors and start as normal by npm run build and npm run start, though as still near for completion the errors and bugs are still currently under fixing.
