### ISSUE TITLE
Admin dashboard 404 on page reload

### ISSUE THREAD

**Issue by Michaeldrm** [Cezerin2/cezerin2-admin#11]
Every time I reload a page on the admin dashboard the page goes 404.

![screenshot from 2019-03-05 18-47-28](https://user-images.githubusercontent.com/4975044/53839853-53bc0580-3f77-11e9-8993-9a1c0ae1694e.png)

**Comment by ngoyal16** [comment]
It's due to the index.html file not found... Need to setup proxy if nothing found send index.html as response

**Comment by vamcart** [comment]
It's not a bug. It's clientside SPA app.
All you can see in your address browser string - virtual.
There is no SSR (Server Side Rendering)

Maybe to add something code to make available reload in browser.

**Comment by LuBuss** [comment]
pm2 doesn't fully support single page application so this is known bug.

Hosting directly or using docker does work correctly

**Comment by vamcart** [comment]
Looks like it's depends of nginx config - https://github.com/Cezerin2/cezerin2-admin/blob/master/nginx/default.conf

root folder of localhost:3002 address attached to /dist folder with builded cezerin2-admin files

var/www/cezerin2-admin/dist

**Comment by vamcart** [comment]
Looks like you required to use web server for your admin app if you want to make URL works correctly at admin app.

**Comment by LuBuss** [comment]
The fix depends on implementation, if running independent then you can fix this by DNS routing or storage config. If running on same instance as API the nginx is required. The docker implementation all ready does most this.

**Comment by vamcart** [comment]
Maybe add some NodeJS server code?!
Like original cezerin?!

Monolith workds fine, including admin side. Without nginx. Page reloading works fine. No 404 error.

**Comment by vamcart** [comment]
We need to fix this problem by default. Because in production mode users can't login to the admin dashboard.

Just see localhost:3002/login 404 error.

**Comment by ngoyal16** [comment]
#21

**Comment by vamcart** [comment]
Thanks! Awesome. It's work now.
