### ISSUE TITLE
Manual: How to add admin login by password!

### ISSUE THREAD

**Issue by vamcart** [Cezerin2/cezerin2-admin#14]
Here is the file with instructions!

[adminlogin.txt](https://github.com/Cezerin2/cezerin2-admin/files/3019418/adminlogin.txt)

P.S. Thanks to dewelloper for share this code!

**Comment by ngoyal16** [comment]
it is good to have it. but passwordless will not be anymore the part of it.

**Comment by doohab** [comment]
How to implement?

**Comment by vamcart** [comment]
Check txt file attached - adminlogin.txt

**Comment by doohab** [comment]
I mean I don't have file called adminlogin.js to replace it with.
Is this different from turning off Developer mode?

**Comment by vamcart** [comment]
Lookd like "Admin login js changed:" is a /cezerin2-dashboard/src/routes/login.js file.
You need to modify this file.

But i don't test this changes and can't say how it's working or working at all.

**Comment by doohab** [comment]
Oh, great thanks. I'm trying to turn off developer mode when I came across this file, so I thought this would be easier, because I can't find a clear way to do it.

**Comment by vamcart** [comment]
You can find step-by-step manuals at https://cezerin.org/docs
+ video manuals - https://www.youtube.com/playlist?list=PLfMqpDnTRYBPDn31L26XsGbKSfvAOJSXu
