### ISSUE TITLE
Dashboard ws://localhost:3002/ws/dashboard?token=null 404 error!

### ISSUE THREAD

**Issue by vamcart** [Cezerin2/cezerin2-admin#15]
I have this error at dashboard side with current github code of cezerin2.

ws://localhost:3002/ws/dashboard?token=null

Dashboard is working fine. But this error displayed at console.

![Screenshot from 2019-04-05 09-22-53](https://user-images.githubusercontent.com/3618501/55607252-672fdb80-5784-11e9-9e64-7fadd6e2384b.png)

**Comment by ngoyal16** [comment]
have to add a check if token is not null then do not try to establish connection using websocket

**Comment by vamcart** [comment]
Why there is no error at original cezerin?!

Maybe some part of code not moved when repos was separated

**Comment by ngoyal16** [comment]
it is also there

**Comment by vamcart** [comment]
https://cezerin.ru/admin
No errors.
Configs the same, devMode is true.

**Comment by LuBuss** [comment]
did you set env
`API_WEB_SOCKET_URL = ws://localhost:3001`

or update admin config
`apiWebSocketUrl: ws://localhost:3001`

**Comment by vamcart** [comment]
Thanks!

Works fine now.

We need to change default config for users who don't use docker.

Change /config/admin.js

	apiWebSocketUrl: process.env.API_WEB_SOCKET_URL || '', // ws://localhost:3001 (in development)
to:

	apiWebSocketUrl: process.env.API_WEB_SOCKET_URL || 'ws://localhost:3001', // ws://localhost:3001 (in development)
