### ISSUE TITLE
Fail to load en_US.js

### ISSUE THREAD

**Issue by tronghuy2807** [Cezerin2/cezerin2-admin#16]
Failed to load plugin url: http://localhost:3002/assets/tinymce/langs/en_US.js at first installation
![Dashboard (2)](https://user-images.githubusercontent.com/6357274/55618622-3621cc00-57c1-11e9-8317-155debc39bab.jpg)

**Comment by vamcart** [comment]
Fixed - https://github.com/Cezerin2/cezerin2-admin/commit/59accbf1e1fbe65c594d54bd9b9504274119cdee

If you have already installed install cezerin2-admin 

Copy en_US.js file to your folders:
 /public/tinymce/langs/en_US.js
 /dist/assets/tinymce/langs/en_US.js
