### ISSUE TITLE
Some issues with image handling

### ISSUE THREAD

**Issue by tronghuy2807** [Cezerin2/cezerin2-admin#17]
- Cannot upload logo
- Cannot display image after uploading:
![Dashboard (1)](https://user-images.githubusercontent.com/6357274/55621505-e85c9200-57c7-11e9-9a8b-8225668d32e6.jpg)
- Cannot delete product image
- After uploading product image, it does not display on box:
![Dashboard (3)](https://user-images.githubusercontent.com/6357274/55621868-e47d3f80-57c8-11e9-9cb0-eb7a5a457d6e.jpg)

**Comment by vamcart** [comment]
Fixed and merged to the current code.
