### ISSUE TITLE
Too many product categories, very slow store.

### ISSUE THREAD

**Issue by Michaeldrm** [Cezerin2/cezerin2-admin#18]
Hello, my store have by default too many product categories, about twenty thousand.. I know it seems too much but this is extremely important for my project to work so, I was looking for a way that the categories could be loaded dynamically. I need the app to load only the parent categories and than search for the children categories only if the user select its parent. How this could be done? I can't administrate categories and my store is running very slow right now. It's almost impossible to use. Any help would be very appreciated!

**Comment by vamcart** [comment]
For this thousands of categories you can't use ANY shopping cart software "out of the box", imho.
You need to modify any shopping cart engine: opencart, magento, prestashop, woocommerce, cezerin etc....

**Comment by LuBuss** [comment]
I dont feel this will be a feature supported by cezerin2. Though I would be happy to help you on implementing a solution.

**Comment by Michaeldrm** [comment]
Thanks for your support! Actually I just need you guys to point me where should I start to modify since all of the separation of the project into different services it's pretty confusing to me yet.

**Comment by LuBuss** [comment]
What you want to do?

**cezerin2**
Update api productCategories _(cezerin2/src/services/products/productCategories.js)_
a. filter parameter to get parent categories
b. filter to get categories of parent

**cezerin2-store**
Update categoryBreadcrumbs to fetch ParentCategories _(cezerin2-store/theme/src/components/categoryBreadcrumbs.js)_

You should really test the api before proceeding to store.

**Comment by Michaeldrm** [comment]
Thank you so much for your help @LuBuss   
The information you gave me is very helpful! One more thing. How can I do the same in the categories admin panel on cezerin2-admin?

**Comment by LuBuss** [comment]
Admin will be the most complicated

You will be required to update `selectCategory` and `deselectCategory` in (cezerin2-admin/src/modules/productCategories/action.js) 

let me know if / when you stuck
