### ISSUE TITLE
Fix the doc for admin panel

### ISSUE THREAD

**Issue by LuBuss** [Cezerin2/cezerin2-admin#3]

**Comment by LuBuss** [comment]
basic notes for development using pm2.
Notes required to be better documented when separated

steps.
1. cezerin2 update /config/server.js // store itself will not work
	// Access-Control-Allow-Origin
	storeBaseUrl: `http://localhost:3003`,
2. build and execute cezerin2
3. build cezerin2-admin
4. run "pm2 serve ./dist 3003"
5. go to url localhost:3003

**Comment by ngoyal16** [comment]
we have to change store to admin when it comes to admin panel

**Comment by thienpow** [comment]
> basic notes for development using pm2.
> Notes required to be better documented when separated
> 
> steps.
> 
> 1. cezerin2 update /config/server.js // store itself will not work
>    // Access-Control-Allow-Origin
>    storeBaseUrl: `http://localhost:3003`,
> 2. build and execute cezerin2
> 3. build cezerin2-admin
> 4. run "pm2 serve ./dist 3003"
> 5. go to url localhost:3003

followed this steps... admin page still not working properly, UI is shown but no login, and every setting page doesn't work with database.

**Comment by LuBuss** [comment]
We are still heavily in development on this. This is not a production implementation and is only a workaround in development, how we implement this is production is still it still to be documented.

But please note this is not usable in the current situation

**Comment by vamcart** [comment]
Updated docs how to install saperated repos - https://cezerin.org/docs/#/
