### ISSUE TITLE
Few little things

### ISSUE THREAD

**Issue by lefcf** [Cezerin2/cezerin2-admin#32]
Hi guys,
please check these and apply if finding them useful

cezerin2-admin\src\modules\head\components\appBar.js
change row 164 
`const productId = pathname.split('/')[3];`
to
`const productId = pathname.split('/')[2];`

----------------------------

cezerin2-admin\src\modules\products\edit\additional\components\form.js
1-st change row 102
`const imageUrl = product && product.images.length > 0 ? product.images[0].url : null;`
to
`const imageUrl = product && product.images && product.images.length > 0	? product.images[0].url	: null;`

2-nd change row 160
`if (currentIds !== newIds) { this.fetchProducts(newIds);`
to
`		if (newIds) {
			if (currentIds) {
				if (JSON.stringify(currentIds) !== JSON.stringify(newIds)) {
					this.fetchProducts(newIds);
				}
			} else {
				this.fetchProducts(newIds);
			}
		}`

3-rd change row 177
`		} else {
			this.setState({
				products: []
			});`
to
`		} else if (this.state.products.length!==0) {
			this.setState({
				products: []
			});			
		}`

-------------------------------------

cezerin2-admin\src\routes\products\edit.js
this component seems to be a good starting point to have editProduct set - here via fetchProduct
the whole file changed to

`
import React from 'react';
import { Route } from 'react-router-dom';
import ProductEdit from 'modules/products/edit';
import ProductOption from 'modules/products/edit/option';
import { connect } from 'react-redux';
import { fetchProduct } from 'modules/products/actions';

class ProductDetails extends React.Component {
	componentDidMount() {
		const id = this.props.match.params.productId;
		this.props.fetchProduct(id);
	}

	render() {
		return (
			<div className="row row--no-gutter col-full-height scroll">
				<div className="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-md-offset-1 col-lg-offset-2">
					<Route path="/product/:productId" exact component={ProductEdit} />
					<Route
						path="/product/:productId/option/:optionId"
						component={ProductOption}
					/>
				</div>
			</div>
		);
	}
}

export default connect(
	null,
	{ fetchProduct }
)(ProductDetails);
`

--------------------------------------------------

on https://react-redux.js.org/using-react-redux/connect-mapstate
there is a table and from there

if using
`(state, ownProps) => stateProps`
 
then
mapStateToProps runs when:
store state changes or any field of ownProps is different
+
component re-renders when:
any field of stateProps is different or any field of ownProps is different

might not correct info for cases when passing in and not using it
but you might want to remove passing ownProps as args when not actually using it as in following

-------------------------------------

cezerin2-admin\src\modules\products\edit\index.js
change  row 62
`const mapStateToProps = (state, ownProps) => ({
	product: state.products.editProduct
});`
to
`const mapStateToProps = (state) => ({
	product: state.products.editProduct
});`

-----------------------------

cezerin2-admin\src\modules\products\edit\additional\index.js
1-st change row 6
`const mapStateToProps = (state, ownProps) => ({`
to
`const mapStateToProps = (state) => ({`

2-nd change row 12
`const mapDispatchToProps = (dispatch, ownProps) => ({`
to
`const mapDispatchToProps = (dispatch) => ({`

----------------------------------

cezerin2-admin\src\modules\products\edit\attributes\index.js
1-st change row 6
`const mapStateToProps = (state, ownProps) => ({`
to
`const mapStateToProps = (state) => ({`

2-nd change row 10
`const mapDispatchToProps = (dispatch, ownProps) => ({`
to
`const mapDispatchToProps = (dispatch) => ({`

-----------------------------------

cezerin2-admin\src\modules\products\edit\general\index.js
1-st change row 6
`const mapStateToProps = (state, ownProps) => ({`
to
`const mapStateToProps = (state) => ({`

2-nd change row 10
`const mapDispatchToProps = (dispatch, ownProps) => ({`
to
`const mapDispatchToProps = (dispatch) => ({`

-------------------------------------

cezerin2-admin\src\modules\products\editHead\index.js
change row 6
`const mapStateToProps = (state, ownProps) => ({`
to
`const mapStateToProps = (state) => ({`

**Comment by LuBuss** [comment]
Thank you, I will update over weekend.
