### ISSUE TITLE
order page is not showing if there is there is no product image

### ISSUE THREAD

**Issue by ngoyal16** [Cezerin2/cezerin2-admin#4]
order page is not showing if there is there is no product image

**Comment by LuBuss** [comment]
I am not experiencing this issue on my end

**Comment by vamcart** [comment]
O have the same problem with old mongodb version 3.2
At mongodb 4 order pages works fine for me.

**Comment by neunygph** [comment]
I have the same issue and I’m using the latest MongoDB on mongo atlas.

**Comment by vamcart** [comment]
Fix for that issue:

in /src/admin/cliens/modules/orders/edit/components/items.js

const imageUrl =
            product && product.images.length > 0 ? product.images[0].url : null;
to:
const imageUrl = product && product.images ? product.images[0].url : null;
