### ISSUE TITLE
How to run admin in https using pm2

### ISSUE THREAD

**Issue by anjiuidev** [Cezerin2/cezerin2-admin#48]
I am using google cloud for hosting my application. For cezeren2 Server and Cezerin2 store I have added SSL certificates and enabled https for them. For these two applications, there is a separate file to start the node server.

While coming to the cezerin2 admin, there is no server config file, I have found process.json with the basic configuration. How to enable https for cezerin2 admin using pm2.

**Comment by anjiuidev** [comment]
Any help on this?

**Comment by vamcart** [comment]
https://demo.cezerin.net
https://admin.cezerin.net
And here is the doc how to configure, sample configs, etc - https://cezerin.org/docs/#/
and - https://github.com/Cezerin2/cezerin2-mono/blob/master/docs/nginx.md
sample config for ssl
