### ISSUE TITLE
import products fail

### ISSUE THREAD

**Issue by cioranique** [Cezerin2/cezerin2-admin#50]
if you click on product import > import button,  all current products gets deleted or disabled from the  store :(

**Comment by lortschi** [comment]
The product importer is working this way. It‘s removing all products and categories first, then it‘s importing the setup categories and ptoducts ftom the google spreadsheet. Otherwise if it‘s won‘ t remove first, then couldn‘t be avoid product duplicates. This is not a bug

**Comment by cioranique** [comment]
alright, i didn't know that, could you please give me an example of a google spreadsheet file?

**Comment by lortschi** [comment]
Can you open this?: https://docs.google.com/spreadsheets/d/1eEa-9dERtjug9rGAycjDjA7L2imu-53-44kkqrmro9c

**Comment by lortschi** [comment]
I will next days extend the Cezerin2 docs and explain the setup in Cezerin2 admin dashboard.  Sorry it was completely forgotten.

**Comment by cioranique** [comment]
yes, it's opened, now i can follow this speadsheet so i can import products, thank you.

**Comment by AllyMao85** [comment]
I wander if deleting all the products and re-import will regenerate objectid which product.id and variant id are on order items. It will be more clear to add an “action” column that you can select “update”, “ delete”, “create” on google sheet and let the import program only process the data is changed and this also reduce the writing lock window.

**Comment by lortschi** [comment]
yes, sure, that would be the best solution. This is just a basic first version of product importer. Please feel free to open a feature issue to do this extension. I will close this here.
